### ISSUE TITLE
RSA Decryption Failed [client 1240.100.30]

### ISSUE THREAD

**Issue by FakeShinoda** [jo3bingham/TibiaAPI#34]
**[Edited]**
In version 1240.100.30 we have 13 new bytes before RSA Key.

We need a version check to change the buffer position from **18** to **31** in Connection.cs
(already check it, and it's working)

--------------------------------------------------------------------------------------------------

After a new client update i getting **RSA Decryption Failed** using Public OTServ RSA
with error data:

**9D 00 00 00 00 00 0A 05 00 D8 04 D8 04 00 00 0B 00 31 6C 6A FA 79 FA 39 E9 B9 6E 7F D4 B0 08 E7 73 CB D9 F4 28 07 65 00 0A B2 94 CF 7E 71 92 CF 81 4D C7 D5 DC 45 F6 E9 02 C0 1F 1E E1 3F 3C 94 AF 29 5B 84 04 4C 91 90 50 A8 61 D4 DE C6 5B B4 5F D7 1B 2F 7C 8C B4 C0 33 3F 28 CC E4 81 85 E3 7D 65 1B 74 3F E8 64 63 D6 80 32 7F C5 A4 01 7E 77 99 98 B4 9E 45 AE 42 B2 2C 84 8E B7 AD 14 02 86 82 21 69 A6 F7 4C 61 1E AC C6 1B B5 D7 6B 50 3D 20 05 37 C3 0D 60 54 3D 42 C1 E6 7B 9A 2F**

**Comment by jlcvp** [comment]
Maybe the otserver you're trying to log in to is using another key

**Comment by FakeShinoda** [comment]
> 
> 
> Maybe the otserver you're trying to log in to is using another key

Im trying in Global Tibia

**Comment by jlcvp** [comment]
Yeah, I've tested here and I'm getting the same error. It looks like something changed on the first packet received from server

**Comment by jo3bingham** [comment]
This has been fixed in commit f71c0b7 that has been pushed to `master`. Thanks for the report!
